/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CircuitProviderObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type CircuitProviderParameters struct {

	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

// CircuitProviderSpec defines the desired state of CircuitProvider
type CircuitProviderSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CircuitProviderParameters `json:"forProvider"`
}

// CircuitProviderStatus defines the observed state of CircuitProvider.
type CircuitProviderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CircuitProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// CircuitProvider is the Schema for the CircuitProviders API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,netbox}
type CircuitProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CircuitProviderSpec   `json:"spec"`
	Status            CircuitProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CircuitProviderList contains a list of CircuitProviders
type CircuitProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CircuitProvider `json:"items"`
}

// Repository type metadata.
var (
	CircuitProvider_Kind             = "CircuitProvider"
	CircuitProvider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CircuitProvider_Kind}.String()
	CircuitProvider_KindAPIVersion   = CircuitProvider_Kind + "." + CRDGroupVersion.String()
	CircuitProvider_GroupVersionKind = CRDGroupVersion.WithKind(CircuitProvider_Kind)
)

func init() {
	SchemeBuilder.Register(&CircuitProvider{}, &CircuitProviderList{})
}
